# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='vServer.proto',
  package='protobuf.socketrpc',
  serialized_pb='\n\rvServer.proto\x12\x12protobuf.socketrpc\"\x16\n\x14GetFilterListRequest\"(\n\x15GetFilterListResponse\x12\x0f\n\x07\x66ilters\x18\x01 \x03(\t2v\n\x0e\x43ommandService\x12\x64\n\rGetFilterList\x12(.protobuf.socketrpc.GetFilterListRequest\x1a).protobuf.socketrpc.GetFilterListResponseB\x1e\n\tcom.capraB\x0cVServerProtoH\x01\x90\x01\x01')




_GETFILTERLISTREQUEST = descriptor.Descriptor(
  name='GetFilterListRequest',
  full_name='protobuf.socketrpc.GetFilterListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=37,
  serialized_end=59,
)


_GETFILTERLISTRESPONSE = descriptor.Descriptor(
  name='GetFilterListResponse',
  full_name='protobuf.socketrpc.GetFilterListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='filters', full_name='protobuf.socketrpc.GetFilterListResponse.filters', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=61,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['GetFilterListRequest'] = _GETFILTERLISTREQUEST
DESCRIPTOR.message_types_by_name['GetFilterListResponse'] = _GETFILTERLISTRESPONSE

class GetFilterListRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETFILTERLISTREQUEST
  
  # @@protoc_insertion_point(class_scope:protobuf.socketrpc.GetFilterListRequest)

class GetFilterListResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETFILTERLISTRESPONSE
  
  # @@protoc_insertion_point(class_scope:protobuf.socketrpc.GetFilterListResponse)


_COMMANDSERVICE = descriptor.ServiceDescriptor(
  name='CommandService',
  full_name='protobuf.socketrpc.CommandService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=103,
  serialized_end=221,
  methods=[
  descriptor.MethodDescriptor(
    name='GetFilterList',
    full_name='protobuf.socketrpc.CommandService.GetFilterList',
    index=0,
    containing_service=None,
    input_type=_GETFILTERLISTREQUEST,
    output_type=_GETFILTERLISTRESPONSE,
    options=None,
  ),
])

class CommandService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _COMMANDSERVICE
class CommandService_Stub(CommandService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _COMMANDSERVICE

# @@protoc_insertion_point(module_scope)
