# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='server.proto',
  package='protobuf.socketrpc',
  serialized_pb='\n\x0cserver.proto\x12\x12protobuf.socketrpc\"1\n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x02(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x14\n\x12IsConnectedRequest\")\n\x13ReloadFilterRequest\x12\x12\n\nfilterName\x18\x01 \x03(\t\"&\n\x10LoadChainRequest\x12\x12\n\nfilterName\x18\x01 \x02(\t\"\x16\n\x14GetFilterListRequest\"(\n\x15GetFilterListResponse\x12\x0f\n\x07\x66ilters\x18\x01 \x03(\t\"%\n#GetFilterListFromFilterChainRequest\"S\n$GetFilterListFromFilterChainResponse\x12+\n\x07\x66ilters\x18\x01 \x03(\x0b\x32\x1a.protobuf.socketrpc.Filter\"#\n\x06\x46ilter\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0b\n\x03\x64oc\x18\x02 \x01(\t2\xa2\x04\n\x0e\x43ommandService\x12\x66\n\x0fget_filter_list\x12(.protobuf.socketrpc.GetFilterListRequest\x1a).protobuf.socketrpc.GetFilterListResponse\x12\x95\x01\n get_filter_list_from_filterchain\x12\x37.protobuf.socketrpc.GetFilterListFromFilterChainRequest\x1a\x38.protobuf.socketrpc.GetFilterListFromFilterChainResponse\x12Z\n\x0cis_connected\x12&.protobuf.socketrpc.IsConnectedRequest\x1a\".protobuf.socketrpc.StatusResponse\x12\\\n\rreload_filter\x12\'.protobuf.socketrpc.ReloadFilterRequest\x1a\".protobuf.socketrpc.StatusResponse\x12V\n\nload_chain\x12$.protobuf.socketrpc.LoadChainRequest\x1a\".protobuf.socketrpc.StatusResponseB\x1e\n\tcom.capraB\x0cVServerProtoH\x01\x90\x01\x01')




_STATUSRESPONSE = descriptor.Descriptor(
  name='StatusResponse',
  full_name='protobuf.socketrpc.StatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='protobuf.socketrpc.StatusResponse.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='protobuf.socketrpc.StatusResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=85,
)


_ISCONNECTEDREQUEST = descriptor.Descriptor(
  name='IsConnectedRequest',
  full_name='protobuf.socketrpc.IsConnectedRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=87,
  serialized_end=107,
)


_RELOADFILTERREQUEST = descriptor.Descriptor(
  name='ReloadFilterRequest',
  full_name='protobuf.socketrpc.ReloadFilterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='filterName', full_name='protobuf.socketrpc.ReloadFilterRequest.filterName', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=109,
  serialized_end=150,
)


_LOADCHAINREQUEST = descriptor.Descriptor(
  name='LoadChainRequest',
  full_name='protobuf.socketrpc.LoadChainRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='filterName', full_name='protobuf.socketrpc.LoadChainRequest.filterName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=152,
  serialized_end=190,
)


_GETFILTERLISTREQUEST = descriptor.Descriptor(
  name='GetFilterListRequest',
  full_name='protobuf.socketrpc.GetFilterListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=192,
  serialized_end=214,
)


_GETFILTERLISTRESPONSE = descriptor.Descriptor(
  name='GetFilterListResponse',
  full_name='protobuf.socketrpc.GetFilterListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='filters', full_name='protobuf.socketrpc.GetFilterListResponse.filters', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=216,
  serialized_end=256,
)


_GETFILTERLISTFROMFILTERCHAINREQUEST = descriptor.Descriptor(
  name='GetFilterListFromFilterChainRequest',
  full_name='protobuf.socketrpc.GetFilterListFromFilterChainRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=258,
  serialized_end=295,
)


_GETFILTERLISTFROMFILTERCHAINRESPONSE = descriptor.Descriptor(
  name='GetFilterListFromFilterChainResponse',
  full_name='protobuf.socketrpc.GetFilterListFromFilterChainResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='filters', full_name='protobuf.socketrpc.GetFilterListFromFilterChainResponse.filters', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=297,
  serialized_end=380,
)


_FILTER = descriptor.Descriptor(
  name='Filter',
  full_name='protobuf.socketrpc.Filter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='protobuf.socketrpc.Filter.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='doc', full_name='protobuf.socketrpc.Filter.doc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=382,
  serialized_end=417,
)

_GETFILTERLISTFROMFILTERCHAINRESPONSE.fields_by_name['filters'].message_type = _FILTER
DESCRIPTOR.message_types_by_name['StatusResponse'] = _STATUSRESPONSE
DESCRIPTOR.message_types_by_name['IsConnectedRequest'] = _ISCONNECTEDREQUEST
DESCRIPTOR.message_types_by_name['ReloadFilterRequest'] = _RELOADFILTERREQUEST
DESCRIPTOR.message_types_by_name['LoadChainRequest'] = _LOADCHAINREQUEST
DESCRIPTOR.message_types_by_name['GetFilterListRequest'] = _GETFILTERLISTREQUEST
DESCRIPTOR.message_types_by_name['GetFilterListResponse'] = _GETFILTERLISTRESPONSE
DESCRIPTOR.message_types_by_name['GetFilterListFromFilterChainRequest'] = _GETFILTERLISTFROMFILTERCHAINREQUEST
DESCRIPTOR.message_types_by_name['GetFilterListFromFilterChainResponse'] = _GETFILTERLISTFROMFILTERCHAINRESPONSE
DESCRIPTOR.message_types_by_name['Filter'] = _FILTER

class StatusResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATUSRESPONSE
  
  # @@protoc_insertion_point(class_scope:protobuf.socketrpc.StatusResponse)

class IsConnectedRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ISCONNECTEDREQUEST
  
  # @@protoc_insertion_point(class_scope:protobuf.socketrpc.IsConnectedRequest)

class ReloadFilterRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RELOADFILTERREQUEST
  
  # @@protoc_insertion_point(class_scope:protobuf.socketrpc.ReloadFilterRequest)

class LoadChainRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOADCHAINREQUEST
  
  # @@protoc_insertion_point(class_scope:protobuf.socketrpc.LoadChainRequest)

class GetFilterListRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETFILTERLISTREQUEST
  
  # @@protoc_insertion_point(class_scope:protobuf.socketrpc.GetFilterListRequest)

class GetFilterListResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETFILTERLISTRESPONSE
  
  # @@protoc_insertion_point(class_scope:protobuf.socketrpc.GetFilterListResponse)

class GetFilterListFromFilterChainRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETFILTERLISTFROMFILTERCHAINREQUEST
  
  # @@protoc_insertion_point(class_scope:protobuf.socketrpc.GetFilterListFromFilterChainRequest)

class GetFilterListFromFilterChainResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETFILTERLISTFROMFILTERCHAINRESPONSE
  
  # @@protoc_insertion_point(class_scope:protobuf.socketrpc.GetFilterListFromFilterChainResponse)

class Filter(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FILTER
  
  # @@protoc_insertion_point(class_scope:protobuf.socketrpc.Filter)


_COMMANDSERVICE = descriptor.ServiceDescriptor(
  name='CommandService',
  full_name='protobuf.socketrpc.CommandService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=420,
  serialized_end=966,
  methods=[
  descriptor.MethodDescriptor(
    name='get_filter_list',
    full_name='protobuf.socketrpc.CommandService.get_filter_list',
    index=0,
    containing_service=None,
    input_type=_GETFILTERLISTREQUEST,
    output_type=_GETFILTERLISTRESPONSE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='get_filter_list_from_filterchain',
    full_name='protobuf.socketrpc.CommandService.get_filter_list_from_filterchain',
    index=1,
    containing_service=None,
    input_type=_GETFILTERLISTFROMFILTERCHAINREQUEST,
    output_type=_GETFILTERLISTFROMFILTERCHAINRESPONSE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='is_connected',
    full_name='protobuf.socketrpc.CommandService.is_connected',
    index=2,
    containing_service=None,
    input_type=_ISCONNECTEDREQUEST,
    output_type=_STATUSRESPONSE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='reload_filter',
    full_name='protobuf.socketrpc.CommandService.reload_filter',
    index=3,
    containing_service=None,
    input_type=_RELOADFILTERREQUEST,
    output_type=_STATUSRESPONSE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='load_chain',
    full_name='protobuf.socketrpc.CommandService.load_chain',
    index=4,
    containing_service=None,
    input_type=_LOADCHAINREQUEST,
    output_type=_STATUSRESPONSE,
    options=None,
  ),
])

class CommandService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _COMMANDSERVICE
class CommandService_Stub(CommandService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _COMMANDSERVICE

# @@protoc_insertion_point(module_scope)
